# Problema 5:

Determine los desplazamientos de los nodos y sus pendientes; las fuerzas en cada elemento y las
reacciones. Tome E = 29x106 psi (libras por pulgada cuadrada) e I = 200 pulgada4


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import copy
GL = 2             # Grados de libertad 
E = 29e6         # psi (libras por pulgada cuadrada)
L = 15           # cm  (por elemento)
I = 200           # pulgada^4 (in^4)
e = 2              # elementos  → → # nodos =e+1
w = 200            # lb/ft

In [4]:
D = np.zeros((e+1)*GL)     # (d, fi, d, fi, ...) desplazamientos, angulos
F = np.zeros((e+1)*GL)     # (F, M, F, M, ...) fuerzas, momentos
KG = np.zeros(((e+1)*GL,(e+1)*GL))
d=[]
f=[]

CC = [[1,0], [1,0], [2,-w*L/2], [2,-w*(L**2)/12], [1,0], [2,0]] # por nodo consecutivamete: [1=d o 2=D, valor conocido], [1=fi, 2=M, valor conocido]
'''
w=1
L=1
e=1
E=1
I=1
CC = [[1,0], [1,0], [2,-w*L/2], [2,w*(L**2)/12]]
'''

for i in range(e):
    KL=(E*I)/(L**3)* np.array( [[12, 6*L, -12, 6*L], [6*L, 4*(L**2), -6*L, 2*(L**2)],
                     [-12, -6*L, 12, -6*L], [6*L, 2*(L**2), -6*L, 4*(L**2)]])
    KG[2*i:2*i+GL*2, 2*i:2*i+GL*2]+= KL
    

j=-1
for i in CC:
    j+=1
    if i[0]==1:
        D[CC.index(i)]=i[1]
        f.append(j)   # f/M desconocidos
    else:
        F[CC.index(i)]=i[1]
        d.append(j)  # d/fi desconocidos
        
dd=np.linalg.solve(KG[np.ix_(d, d)], F[d] )

D[d]=dd  # desplazamientos finales

FF=np.dot(KG, D)  # fuerzas finales.

ECU=[-(w*L)/2, -w*(L**2)/12, -(w*L)/2,  w*(L**2)/12]

R=np.zeros((e+1)*GL)
for i in range(e):
    R[i*GL:i*GL+4]=FF[i*GL:i*GL+4] - ECU

[0. 0. 0. 0. 0. 0.] [    0.     0. -1500. -3750.     0.     0.]


In [3]:
D, FF, R

(array([ 0.00000000e+00,  0.00000000e+00, -6.81910022e-05, -3.33378233e-06,
         0.00000000e+00,  8.48599138e-06]),
 array([  890.625,  7968.75 , -1500.   , -3750.   ,   609.375,     0.   ]),
 array([ 2.39062500e+03,  1.17187500e+04,  4.54747351e-13,  0.00000000e+00,
         2.10937500e+03, -3.75000000e+03]))

In [27]:
d

0.08333333333333333

In [12]:
R

array([0., 0., 0., 0., 0., 0.])