# Problema 4

Determine los desplazamientos y rotaciones y fuerzas y torques de vínculos para el sistema de lafigura. Tome E = 210 GPa e I = 2 x 10–4 m4. 

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import copy
GL = 2             # Grados de libertad 
E = 210e9          # GPa
#MDF_COMMENT ojo las unidades ! L = 300            # cm  (por elemento)
L = 3
I = 2e-4           # m^4
e = 2              # elementos  → → # nodos =e+1

In [13]:
D = np.zeros((e+1)*GL)     # (d, fi, d, fi, ...) desplazamientos, angulos
F = np.zeros((e+1)*GL)     # (F, M, F, M, ...) fuerzas, momentos
KG = np.zeros(((e+1)*GL,(e+1)*GL))
#MDF_COMMENT cuidado, que en este ejercicio tenías un elmento mas con el resorte !
d=[]
f=[]

for i in range(e):
    KL=(E*I)/(L**3)* np.array( [[12, 6*L, -12, 6*L], [6*L, 4*(L**2), -6*L, 2*(L**2)],
                     [-12, -6*L, 12, -6*L], [6*L, 2*(L**2), -6*L, 4*(L**2)]])
    #MDF_COMMENT creo que te falta el último elemento, no ?
    KG[2*i:2*i+GL*2, 2*i:2*i+GL*2]+= KL
    
CC = [[1,0], [1,0], [1,0], [2,0], [2,-50000], [1,0]] # por nodo consecutivamete: [1=d o 2=D, valor conocido], [1=fi, 2=M, valor conocido]

j=-1
for i in CC:
    j+=1
    if i[0]==1:
        D[CC.index(i)]=i[1]
        f.append(j)   # f/M desconocidos
    else:
        F[CC.index(i)]=i[1]
        d.append(j)  # d/fi desconocidos
        
dd=np.linalg.solve(KG[np.ix_(d, d)], F[d] )

D[d]=dd  # desplazamientos finales

FF=np.dot(KG, D)  # fuerzas finales.

In [14]:
FF

array([-30000., -30000.,  80000.,      0., -50000.,  90000.])

In [15]:
np.set_printoptions(precision=2, linewidth=100)
KG

array([[ 1.87e+07,  2.80e+07, -1.87e+07,  2.80e+07,  0.00e+00,  0.00e+00],
       [ 2.80e+07,  5.60e+07, -2.80e+07,  2.80e+07,  0.00e+00,  0.00e+00],
       [-1.87e+07, -2.80e+07,  3.73e+07,  0.00e+00, -1.87e+07,  2.80e+07],
       [ 2.80e+07,  2.80e+07,  0.00e+00,  1.12e+08, -2.80e+07,  2.80e+07],
       [ 0.00e+00,  0.00e+00, -1.87e+07, -2.80e+07,  1.87e+07, -2.80e+07],
       [ 0.00e+00,  0.00e+00,  2.80e+07,  2.80e+07, -2.80e+07,  5.60e+07]])

In [16]:
KG/KG.max()

array([[ 0.17,  0.25, -0.17,  0.25,  0.  ,  0.  ],
       [ 0.25,  0.5 , -0.25,  0.25,  0.  ,  0.  ],
       [-0.17, -0.25,  0.33,  0.  , -0.17,  0.25],
       [ 0.25,  0.25,  0.  ,  1.  , -0.25,  0.25],
       [ 0.  ,  0.  , -0.17, -0.25,  0.17, -0.25],
       [ 0.  ,  0.  ,  0.25,  0.25, -0.25,  0.5 ]])