In [1]:
import numpy as np
import gmsh

gmsh.initialize() #inicia Gmsh
gmsh.model.add('PROBLEMA2') #genera el modelo


# Generado de la figura
L1 = 10
L2 = 5
r = 1
#Lc = 20 #caso del ejercicio
Lc = 1
Lcr = 1  #Refina aun mas el mallado cerca del circulo

#chapa
p1 = gmsh.model.geo.addPoint(0, 0, 0, Lc)
p2 = gmsh.model.geo.addPoint(0, L2, 0, Lc) 
p3 = gmsh.model.geo.addPoint(L1, L2, 0, Lc) 
p4 = gmsh.model.geo.addPoint(L1, 0, 0, Lc)

#circulo
p5 = gmsh.model.geo.addPoint(0,r,0,Lcr)
p6 = gmsh.model.geo.addPoint(r,0,0,Lcr)


l1 = gmsh.model.geo.addLine(p5, p2)
l2 = gmsh.model.geo.addLine(p2, p3)
l3 = gmsh.model.geo.addLine(p3, p4)
l4 = gmsh.model.geo.addLine(p4, p6)

semi1 = gmsh.model.geo.addCircleArc(p5,p1 ,p6) 


C1 = gmsh.model.geo.addCurveLoop([l1, l2, l3, l4])
C2 = gmsh.model.geo.addCurveLoop([semi1])

S1 = gmsh.model.geo.addPlaneSurface([C1,C2]) #asi se genera la superifice descontando el circulo


#Generado de las condiciones de contorno

Empotradox = gmsh.model.addPhysicalGroup(1, [l1]) #1 es para curva o linea!
gmsh.model.setPhysicalName(1,Empotradox,'Empotradox')


Empotradoy = gmsh.model.addPhysicalGroup(1, [l4]) #1 es para curva o linea!
gmsh.model.setPhysicalName(1,Empotradoy,'Empotradoy')


Traccionado = gmsh.model.addPhysicalGroup(1, [l3])
gmsh.model.setPhysicalName(1,Traccionado,'Traccionado') #esta funcion le pone nombre a todos los nodos aca


Superficie = gmsh.model.addPhysicalGroup(2,[S1]) #2 es para superficies!
gmsh.model.setPhysicalName(2,Superficie, 'Superficie')


gmsh.model.geo.synchronize() #sincroniza lo que creamos con el modelo que creamos arriba
gmsh.model.mesh.generate(2)

In [2]:
NodeInfo = gmsh.model.mesh.get_nodes()
NodeInfo[1].shape
NumeroNodos = NodeInfo[0].shape[0]
MN = NodeInfo[1].reshape(NumeroNodos , 3)


ElementInfo = gmsh.model.mesh.get_elements()
ETAGS, ELEMENTS = gmsh.model.mesh.get_elements_by_type(2)
MC = ELEMENTS.reshape([ETAGS.shape[0],3])

#Empotrados
NodosIzquierda = gmsh.model.mesh.get_nodes_for_physical_group(1,Empotradox)
A = NodosIzquierda[0].reshape(-1,1)
B = np.zeros((len(A),1))
MNEx = np.concatenate((A,B) , axis = 1)

NodosAbajo = gmsh.model.mesh.get_nodes_for_physical_group(1,Empotradoy)
J = NodosAbajo[0].reshape(-1,1)
T = np.zeros((len(J),1))
MNEy = np.concatenate((J,T) , axis = 1)


MNE = np.concatenate((MNEx,MNEy) , axis = 0)

#Traccionados

'''ya de entrada aca hay algo mal, la ultima longitud pese a ser un mallado sietrico es de 3 y no de 1 por lo tanto las fuerzas estan mal'''

entityTraccionada = gmsh.model.getEntitiesForPhysicalGroup(1, Traccionado)
Tgroup, Ttraccionada, Ltraccionada = gmsh.model.mesh.getElements(1, entityTraccionada[0])
Ltraccionada = Ltraccionada[0].reshape(Ttraccionada[0].shape[0],2)
Longitudes = np.abs( MN[Ltraccionada[:,0]-1,1] - MN[Ltraccionada[:,1]-1,1] )
espesor = 1
tension = 1000 #Pa

NodosTraccionados = gmsh.model.mesh.get_nodes_for_physical_group(1, Traccionado)

C = NodosTraccionados[0].reshape(-1,1)
D = np.zeros((len(C),2))
MNT = np.concatenate((C,D) , axis = 1)
for l in range(len(Longitudes)):
    MNT[l,1] = tension*espesor*Longitudes[l]
    
MNT[0,1] = tension*espesor*Longitudes[1]*1/2
MNT[len(C)-1,1] = tension*espesor*Longitudes[len(Longitudes)-1]*1/2
print(MNT)

Nodoslibres = []


'''la idea aca es tomar todos los nodos del centro asignarles fuerza 0 y agregegarlos a MNT incluidos los nodos empotrados ya que luego los discriminare cuando arme el vector fuerzas'''
Nodos = gmsh.model.mesh.get_nodes_for_physical_group(2, Superficie)
for i in Nodos[0]:
    if i in NodosTraccionados[0]:
        l = 0
    else:
        Nodoslibres.append(i)
        
E = np.array(Nodoslibres).reshape(-1,1)
D = np.zeros((len(E),2))
Interior = np.concatenate((E,D) , axis = 1)
MNT = np.concatenate((Interior,MNT) , axis = 0)


[[2.0e+00 5.0e+02 0.0e+00]
 [3.0e+00 1.0e+03 0.0e+00]
 [1.8e+01 1.0e+03 0.0e+00]
 [1.9e+01 1.0e+03 0.0e+00]
 [2.0e+01 3.0e+03 0.0e+00]
 [2.1e+01 1.5e+03 0.0e+00]]


In [3]:
E = 30E6
v = 0.3

D = (E/(1-v**2))*np.array([[1,v,0],[v,1,0],[0,0,(0.5*(1-v))]])
Matriz_coordenadas = np.ones((3,3))
Matriz_global = np.zeros([2*len(MN),2*len(MN)])
Matrices_Bloc = []
Areas = []

In [4]:
for l in range (len(MC)):
    
    I,M,J = MC[l]  
    
    i = int(I - 1) ; m = int(M - 1) ; j = int(J - 1)
    
    x = np.array([MN[i,0],MN[m,0],MN[j,0]])
    y = np.array([MN[i,1],MN[m,1],MN[j,1]])

    Bi = y[1] - y[2] ;   Bm = y[2] - y[0] ;    Bj = y[0] - y[1]
    Gi = x[2] - x[1] ;   Gm = x[0] - x[2] ;    Gj = x[1] - x[0]      
    Matriz_coordenadas[:,0] = x
    Matriz_coordenadas[:,1] = y
    
    
    Area = np.linalg.det(Matriz_coordenadas)/2
    
    Matriz1 = (1/(2*Area)) * np.array([[Bi,0,Bm,0,Bj,0],[0,Gi,0,Gm,0,Gj],[Gi,Bi,Gm,Bm,Gj,Bj]])
    Matrices_Bloc.append(Matriz1)
    Matriz_local = espesor * abs(Area) * (np.dot(np.transpose(Matriz1), np.dot(D,Matriz1)))

    A_G = np.array([i*2,i*2+1,m*2,m*2+1,j*2,j*2+1]) #aca pasa algo raro
    Matriz_global[np.ix_(A_G,A_G)] += Matriz_local
    

In [5]:
Desplazamientos_f = np.zeros(len(MN)*2)
Fuerza = []
Nodos = []

for i in MNE:
    
    Nodo,valor = i 
    nodo = int(Nodo-1)
    
    if Nodo in NodosIzquierda[0]:
        Desplazamientos_f[2*nodo] = valor '''valor en x es nulo'''

    elif Nodo in NodosAbajo[0]:
        Desplazamientos_f[2*nodo+1] = valor '''valor en y es nulo'''

'''Aca armo el vector fuerzas, si el nodo es alguno empotrado solo tomo el valor x o y respectivamente y le asigno un valor igual a 0'''
for i in MNT:
    Nodo,valorx,valory = i
    nodo = int(Nodo-1)
    
    if Nodo in NodosIzquierda[0]:
        Fuerza.append(0)
        Nodos.append(2*nodo+1) # para los nodos a la izquierda la fuerza en y es 0
    elif Nodo in NodosAbajo[0]:
        Fuerza.append(0)
        Nodos.append(2*nodo)   # para los nodos abajo la fuerza en x es nula
    else:
        Fuerza.append(valorx)
        Fuerza.append(valory)
        Nodos.append(2*nodo)
        Nodos.append(2*nodo+1) 

    
Fuerza = np.array(Fuerza).reshape(-1,1)

Matriz_res = Matriz_global[np.ix_(Nodos,Nodos)]

Desplazamientos_parcial = np.linalg.solve(Matriz_res,Fuerza)


o = 0
for i in Nodos:
        Desplazamientos_f[i] = Desplazamientos_parcial [o]
        o += 1


Fuerzas_ = np.dot(Matriz_global,Desplazamientos_f)
#print(Fuerzas_.round(4))
#print()
#
#print(Desplazamientos_f)

In [6]:
#Esfuerzos

Tensiones = []

for p in range(len(MC)):
    
    I,M,J = MC[p]    
    
    i = int(I - 1) ; m = int(M - 1) ; j = int(J - 1)

    
    nodos = [2*i,2*i+1,2*m,2*m+1,2*j,2*j+1]
    
    
    A = np.dot(Matrices_Bloc[p],Desplazamientos_f[nodos])
    
    B = np.dot(D,A)

   
    Tensiones.append(B)

Tensiones_ = np.array(Tensiones)

# for i in range (len(Tensiones)):
#    print(Tensiones[i])
#    print()

In [7]:
Problema2 = gmsh.view.add("Problema2")

problema2 = gmsh.view.addModelData(Problema2, 0, 'PROBLEMA2', 'ElementData', ETAGS, Tensiones_[:,0].reshape(-1,1) , numComponents=1)
#agrega todos los datos , el 0 viene de dependencias temporarles aca es 0 no varia con t



In [8]:
Desplazamientos = np.zeros((len(MN),3))

for i in range(len(MN)):
    Desplazamientos[i] = [Desplazamientos_f[i*2],Desplazamientos_f[i*2+1],0]

Problema12 = gmsh.view.add("Problema2")

problema12 = gmsh.view.addModelData(Problema12, 0, 'PROBLEMA2', 'NodeData', NodeInfo[0], Desplazamientos  , numComponents=3)
#agrega todos los datos , el 0 viene de dependencias temporarles aca es 0 no varia con t



In [ ]:
gmsh.fltk.run() 