In [20]:
import numpy as np
np.set_printoptions(precision=2, linewidth=100)

In [21]:
M = np.random.rand(6,6)

In [22]:
M

array([[0.36, 0.51, 0.51, 0.78, 0.08, 0.54],
       [0.81, 0.01, 0.63, 0.52, 0.04, 0.04],
       [0.29, 0.7 , 0.21, 0.71, 0.71, 0.94],
       [0.51, 0.33, 0.63, 0.34, 0.98, 0.18],
       [0.38, 0.39, 0.51, 0.35, 0.48, 0.31],
       [0.64, 0.8 , 0.86, 0.38, 0.72, 0.73]])

In [6]:
M[0:1,2:3]

array([[0.4554924]])

In [24]:
for i in [0,1,2]:
    for j in [0,1,2]:
        I  = [2*i, 2*i+1] #np.linspace(2*i, 2*i+1, 2)#[0,1]
        J  = [2*j, 2*j+1]
        print('I : ', I, 'J: ', J)
        print( M [np.ix_(I, J)] )
        print('-------------------')

I :  [0, 1] J:  [0, 1]
[[0.36 0.51]
 [0.81 0.01]]
-------------------
I :  [0, 1] J:  [2, 3]
[[0.51 0.78]
 [0.63 0.52]]
-------------------
I :  [0, 1] J:  [4, 5]
[[0.08 0.54]
 [0.04 0.04]]
-------------------
I :  [2, 3] J:  [0, 1]
[[0.29 0.7 ]
 [0.51 0.33]]
-------------------
I :  [2, 3] J:  [2, 3]
[[0.21 0.71]
 [0.63 0.34]]
-------------------
I :  [2, 3] J:  [4, 5]
[[0.71 0.94]
 [0.98 0.18]]
-------------------
I :  [4, 5] J:  [0, 1]
[[0.38 0.39]
 [0.64 0.8 ]]
-------------------
I :  [4, 5] J:  [2, 3]
[[0.51 0.35]
 [0.86 0.38]]
-------------------
I :  [4, 5] J:  [4, 5]
[[0.48 0.31]
 [0.72 0.73]]
-------------------


In [15]:
M[np.ix_([0,1],[2,3])]

array([[0.4554924 , 0.54306003],
       [0.38067492, 0.55509906]])

In [25]:
M3 = np.random.rand(8,8)

In [26]:
M3

array([[0.81, 0.1 , 0.97, 0.16, 0.83, 0.73, 0.21, 0.5 ],
       [0.3 , 0.16, 0.34, 0.5 , 0.65, 0.83, 0.68, 0.06],
       [0.77, 0.36, 0.69, 0.01, 0.15, 0.08, 0.92, 0.27],
       [0.42, 0.17, 0.31, 0.88, 0.82, 0.05, 0.67, 0.56],
       [0.24, 0.94, 0.68, 0.24, 0.51, 0.91, 0.3 , 0.74],
       [0.8 , 0.75, 0.41, 0.15, 0.71, 0.69, 0.56, 0.8 ],
       [0.52, 0.49, 0.15, 0.11, 0.34, 0.8 , 0.39, 0.37],
       [0.02, 0.12, 0.62, 0.  , 0.82, 0.98, 0.94, 0.93]])

In [33]:
for i in [0,1]:
    for j in [0,1]:
        I  = np.linspace(4*i, 4*(i+1)-1, 4).astype(int) #np.linspace(2*i, 2*i+1, 2)#[0,1]
        J  = np.linspace(4*j, 4*(j+1)-1, 4).astype(int) #[2*j, 2*j+1]
        print('I : ', I, '; J: ', J)
        print( M3 [np.ix_(I, J)] )
        print('-------------------')

I :  [0 1 2 3] ; J:  [0 1 2 3]
[[0.81 0.1  0.97 0.16]
 [0.3  0.16 0.34 0.5 ]
 [0.77 0.36 0.69 0.01]
 [0.42 0.17 0.31 0.88]]
-------------------
I :  [0 1 2 3] ; J:  [4 5 6 7]
[[0.83 0.73 0.21 0.5 ]
 [0.65 0.83 0.68 0.06]
 [0.15 0.08 0.92 0.27]
 [0.82 0.05 0.67 0.56]]
-------------------
I :  [4 5 6 7] ; J:  [0 1 2 3]
[[0.24 0.94 0.68 0.24]
 [0.8  0.75 0.41 0.15]
 [0.52 0.49 0.15 0.11]
 [0.02 0.12 0.62 0.  ]]
-------------------
I :  [4 5 6 7] ; J:  [4 5 6 7]
[[0.51 0.91 0.3  0.74]
 [0.71 0.69 0.56 0.8 ]
 [0.34 0.8  0.39 0.37]
 [0.82 0.98 0.94 0.93]]
-------------------


# Lectura de datos de un archivo
 y escritura

In [37]:
np.savetxt('M3_randdom.dat', M3, fmt='%8.3f')

In [38]:
M3R = np.loadtxt('M3_randdom.dat')

In [39]:
M3R

array([[0.81, 0.1 , 0.97, 0.16, 0.83, 0.73, 0.21, 0.5 ],
       [0.3 , 0.16, 0.34, 0.5 , 0.65, 0.83, 0.68, 0.06],
       [0.77, 0.36, 0.69, 0.01, 0.15, 0.08, 0.92, 0.27],
       [0.42, 0.17, 0.31, 0.88, 0.82, 0.05, 0.67, 0.56],
       [0.24, 0.94, 0.68, 0.24, 0.51, 0.91, 0.3 , 0.74],
       [0.8 , 0.75, 0.41, 0.15, 0.71, 0.69, 0.56, 0.8 ],
       [0.52, 0.49, 0.15, 0.12, 0.34, 0.8 , 0.39, 0.37],
       [0.02, 0.12, 0.62, 0.  , 0.82, 0.97, 0.94, 0.93]])